// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkcYhwCV_fawfiPpOYHKjG_2WB45p75nc',
    appId: '1:780858448330:web:b436e29f7f39ce6ca59733',
    messagingSenderId: '780858448330',
    projectId: 'login-firebase-c7bd4',
    authDomain: 'login-firebase-c7bd4.firebaseapp.com',
    storageBucket: 'login-firebase-c7bd4.appspot.com',
    measurementId: 'G-3YRGVYL752',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqcGMJvyzCP6pDwsJeT57FRUJp0kpcNk0',
    appId: '1:780858448330:android:6afa84c85143f8b6a59733',
    messagingSenderId: '780858448330',
    projectId: 'login-firebase-c7bd4',
    storageBucket: 'login-firebase-c7bd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVEQAHs3iZ4rEQRx40pecgFPADCQHtKPA',
    appId: '1:780858448330:ios:02c686f497bc97d5a59733',
    messagingSenderId: '780858448330',
    projectId: 'login-firebase-c7bd4',
    storageBucket: 'login-firebase-c7bd4.appspot.com',
    iosClientId: '780858448330-3bbkopo4esnh7643tpou3sj7k6dtbmpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxLevel3Login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVEQAHs3iZ4rEQRx40pecgFPADCQHtKPA',
    appId: '1:780858448330:ios:cd5402321421c1bda59733',
    messagingSenderId: '780858448330',
    projectId: 'login-firebase-c7bd4',
    storageBucket: 'login-firebase-c7bd4.appspot.com',
    iosClientId: '780858448330-r8lr36802q9brh03tm85e93a24496pvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxLevel3Login.RunnerTests',
  );
}
