// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRxmI5fEZ9JlXl2ujjHPX-THUo8SWnA38',
    appId: '1:475476837944:web:eaae99e7e5a12aab86c8cd',
    messagingSenderId: '475476837944',
    projectId: 'chatapp-946ec',
    authDomain: 'chatapp-946ec.firebaseapp.com',
    storageBucket: 'chatapp-946ec.appspot.com',
    measurementId: 'G-CVE8W0N1RP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9i68P8v44ox7cyNU539JeSUr1Ai0qhx4',
    appId: '1:475476837944:android:530309884ab6a75e86c8cd',
    messagingSenderId: '475476837944',
    projectId: 'chatapp-946ec',
    storageBucket: 'chatapp-946ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3A_1cwD7_4aZLxKiVvpPGauIU2r1NiKA',
    appId: '1:475476837944:ios:26e3bf59b274056486c8cd',
    messagingSenderId: '475476837944',
    projectId: 'chatapp-946ec',
    storageBucket: 'chatapp-946ec.appspot.com',
    iosClientId: '475476837944-1je0klfhjec13ren0k6vd3afit7gj1l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3A_1cwD7_4aZLxKiVvpPGauIU2r1NiKA',
    appId: '1:475476837944:ios:59dd04f2dcf409ea86c8cd',
    messagingSenderId: '475476837944',
    projectId: 'chatapp-946ec',
    storageBucket: 'chatapp-946ec.appspot.com',
    iosClientId: '475476837944-dd3e0uto9rr0bn926eqmco3qe8ehdavr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFirebase.RunnerTests',
  );
}
