import 'package:book_store/domain/model/simple_store.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'map_ui_event.freezed.dart';
@freezed
sealed class MapUiEvent with _$MapUiEvent {
  const factory MapUiEvent.clickMaka(SimpleStore simpleStore) = ClickMaka;
  const factory MapUiEvent.clickContainer(int id) = ClickContainer;
  const factory MapUiEvent.switchRadius(int radius) = SwitchRadius;


}