import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'map_ui_event.freezed.dart';
@freezed
sealed class MapUiEvent with _$MapUiEvent {
  const factory MapUiEvent.clickMaka() = ClickMaka;


}