// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK5IFlNsDbrWLPWBO6_s_YeE_nUJxmE9s',
    appId: '1:926027391388:android:951c21c76a8be527092859',
    messagingSenderId: '926027391388',
    projectId: 'bhgh-7a4bc',
    storageBucket: 'bhgh-7a4bc.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK-zpHdYd4fqC_KyRRR-pKLpPl2tDdzMo',
    appId: '1:926027391388:web:b77cadab7b1ddb8c092859',
    messagingSenderId: '926027391388',
    projectId: 'bhgh-7a4bc',
    authDomain: 'bhgh-7a4bc.firebaseapp.com',
    storageBucket: 'bhgh-7a4bc.appspot.com',
    measurementId: 'G-T4CZKBM9C7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAERJ51OdwPYgdxw7qfrX53J11LlkJgQh4',
    appId: '1:926027391388:ios:b375dc1b642a47e1092859',
    messagingSenderId: '926027391388',
    projectId: 'bhgh-7a4bc',
    storageBucket: 'bhgh-7a4bc.appspot.com',
    iosBundleId: 'com.example.bhgh',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAERJ51OdwPYgdxw7qfrX53J11LlkJgQh4',
    appId: '1:926027391388:ios:b375dc1b642a47e1092859',
    messagingSenderId: '926027391388',
    projectId: 'bhgh-7a4bc',
    storageBucket: 'bhgh-7a4bc.appspot.com',
    iosBundleId: 'com.example.bhgh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK-zpHdYd4fqC_KyRRR-pKLpPl2tDdzMo',
    appId: '1:926027391388:web:32fe0b16017f3f58092859',
    messagingSenderId: '926027391388',
    projectId: 'bhgh-7a4bc',
    authDomain: 'bhgh-7a4bc.firebaseapp.com',
    storageBucket: 'bhgh-7a4bc.appspot.com',
    measurementId: 'G-WHZYTNC1G8',
  );

}