import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'board_detail_ui_event.freezed.dart';
@freezed
sealed class BoardDetailUiEvent with _$BoardDetailUiEvent {
  const factory BoardDetailUiEvent.likeTap(bool isLiked) = LikeTap;
}